### ISSUE TITLE
Support non-latin domain names (e.g. cyrillic, arabic)

### ISSUE THREAD

**Issue by olsh** [mat/besticon#10]
It seems like it doesn't work with non-latin domain names.
Here is a couple of examples:

https://icons.better-idea.org/icon?url=http://موقع.وزارة-الأتصالات.مصر/&size=120
https://icons.better-idea.org/icon?url=http://минобрнауки.рф/&size=120

Here are direct links to the sites:
http://موقع.وزارة-الأتصالات.مصر/
http://минобрнауки.рф/

**Comment by mat** [comment]
Unfortunately, this is kind of a known limitation, which I probably should mention somewhere :-(

For this to work we need

- [ ] (new) font(s) that supports those characters (easy?)
- [ ] select a 'character prefix' that makes sense in all languages (not easy for me, need help)

**Comment by olsh** [comment]
We could use this fonts:
https://www.google.com/get/noto/

What do you mean by `character prefix`? Is there an algorithm that gets symbol for icon generation?

**Comment by mat** [comment]
Thanks for the Noto recommendation, looks quite usable.

What I mean regarding the prefix is: To somebody familiar with the language, would this be a correct test case for  [TestMainLetterFromURL](https://github.com/mat/besticon/blob/unicode_lettericons/lettericon/lettericon_test.go#L110-L121)

```go
assertEquals(t, `м`, MainLetterFromURL(`http://минобрнауки.рф/`))
```

**Comment by olsh** [comment]
Yes, this test case is correct.

**Comment by mat** [comment]
I've made some progress on cyrillic support [on this branch](https://github.com/mat/besticon/compare/unicode_lettericons) which I've also [deployed on Heroku ](http://iconserver.herokuapp.com/icons?url=http%3A%2F%2Fминобрнауки.рф#result)

Please feel free to play around, maybe you can find a bug or two.

However I've still trouble supporting `http://موقع.وزارة-الأتصالات.مصر/` as you can see which is mainly because the main Noto font I am using does not seem to support this language, which I believe is an arabic dialect? Do you have other examples of arabic domains?

**Comment by olsh** [comment]
> Please feel free to play around, maybe you can find a bug or two.
It seems like it works just fine! Thanks! 👍 

Sadly, I don't know arabic languages, it was just an example. 
So, I can't help you with it.

**Comment by mat** [comment]
I've moved the apparently more complicated support for arabic to a separate ticket: #13 
Thanks @olsh for your effort and input!
