### ISSUE TITLE
Issue with capitalized attributes

### ISSUE THREAD

**Issue by Jacketbg** [mat/besticon#22]
Some websites use uppercase in their markup, like this:

`<link rel="SHORTCUT ICON" href="/images/layout/favicon.ico" />`

The offending website is http://www.dnevnik.bg/.
besticon decides that it will use http://www.dnevnik.bg/favicon.ico, which is some generic icon, probably from their framework. The correct icon should be http://www.dnevnik.bg/images/layout/favicon.ico

**Proposed fix**: Please ignore case when looking for attributes.

**Comment by mat** [comment]
Thanks @Jacketbg, this is a great bug report and a reasonable request 😀
I am going to try to work soon on it.

**Comment by Jacketbg** [comment]
That's great to hear! Let me know if I can help with something.

**Comment by mat** [comment]
Hey @Jacketbg, I've just implemented it - in an extremely straightforward fashion as you can see ;-).

Unfortunately, this does not change a lot for your example case. Yes, it does find the additional icon but because it's smaller than the other one it won't really get used...

**Before**
<img width="754" alt="before" src="https://cloud.githubusercontent.com/assets/23060/25071178/c732180a-22b0-11e7-8533-1294ba766d6b.png">

**After**
<img width="724" alt="after" src="https://cloud.githubusercontent.com/assets/23060/25071177/c7116c4a-22b0-11e7-8422-5ae6768c925b.png">

**Comment by Jacketbg** [comment]
Thanks for the quick fix mat! Don't worry about the particular case. I'll notify the site owners to fix the mess. Do you plan to make this as a release?

**Comment by mat** [comment]
You're welcome, I just packaged a new release: https://github.com/mat/besticon/releases/tag/v3.3.0

**Comment by Jacketbg** [comment]
Many thanks!
