### ISSUE TITLE
Cannot find icon for a LiveJournal blog

### ISSUE THREAD

**Issue by Jacketbg** [mat/besticon#23]
LiveJournal is possibly the biggest Russian blogging platform. They have a generic favicon and personalized favicons for bloggers to choose from. Currently besticon doesn't detect the personalized icon. Here's an example:

Site: http://ibigdan.livejournal.com/
Besticon: https://icons.better-idea.org/allicons.json?url=ibigdan.livejournal.com
Link: `<link rel="icon" type="image/gif" href="http://l-stat.livejournal.net/img/userinfo_v8.svg?v=17080?v=146.5">`

**Comment by mat** [comment]
Hey, the problem here is that the particular image is an SVG image, this is why the image gets ignored. Adding support for the SVG would need a lot of changes while not a lot of sites offer an SVG icon at this moment, which is why I don't plan to add this in the near future - but maybe the later future ;-)
