### ISSUE TITLE
Mobile User Agent

### ISSUE THREAD

**Issue by bolismauro** [mat/besticon#26]
Hi! 
Really nice work, well done!

We noticed that some websites (e.g., www.google.com) returns the touch-icons only when the user agent is a mobile one. This means that querying google.com with best-icon will return a poor quality image ([this](https://www.google.it/images/branding/product/ico/googleg_lodp.ico)), while  it should be possible to have a better icon just by using a mobile user agent ([this](https://www.google.it//images/branding/product_ios/3x/gsa_ios_60dp.png)).

Would it be possible to expose a parameter to control the used user agent?

**Comment by mat** [comment]
Hi @bolismauro, glad you like it so much, thanks for writing in!

I want to keep it super simple to the end user and I am willing to try a lot of things to achieve this, that's why I hesitate to expose a new parameter to the already large API, I'd rather, for example

1. Keep a server side mapping of domains -> user agent strings
2. Automatically do two queries with different user agent strings
3. Try to find a user agent string that _always_ gives best results

I've changed the user agent once in #12 already but I am an optimist and hope that option 3. is still possible 😉

What do you think? What User Agent did you try?

**Comment by bolismauro** [comment]
The number 1 is a no-go imho, since it would require to keep it updated.

2 and 3 are possible.
In general the better quality images are the apple-touch-icons AFAIK, and they are served for Apple device user agents. In my test I tried with the safari emulation mode, emulating an iPad

**Comment by mat** [comment]
That makes sense, thanks so much for your research.

I will close this issue and will revisit the approach next time a user agent funniness pops up.
