### ISSUE TITLE
What is HOST_ONLY_DOMAINS ?

### ISSUE THREAD

**Issue by kspearrin** [mat/besticon#27]
I see in the `README` there is a an environment variable we can set for `HOST_ONLY_DOMAINS`.

> HOST_ONLY_DOMAINS 
> Comma-separated list of domains where requests for http://example.com/foobar will be rewritten to http://example.com

I still don't really understand what this is for. Can you explain further? What would I need to use this for?

PS, thanks for the awesome Docker image. I got this up and running in minutes on [Azure Web Apps for Containers](https://azure.microsoft.com/en-us/services/app-service/containers/)!

**Comment by mat** [comment]
Fair question, glad to hear the Docker image is working well for you.

HOST_ONLY_DOMAINS was added because https://icons.better-idea.org is running into rate limiting on certain popular sites.

When a domain appears in HOST_ONLY_DOMAINS it means requests for this whole domain will essentially ignore the path and query part of the URI. So while you might be asking for an icon for a certain page at www.example.com/some/page.html you will only ever get the icon for www.example.com (should it exist).

Another option for the future is to remove HOST_ONLY_DOMAINS and make this the default API behaviour. However, I did not want to break existing clients.

I just added the current list of domains to https://github.com/mat/besticon/blob/master/HOST_ONLY_DOMAINS for reference.

**Comment by kspearrin** [comment]
Thanks for the info. It makes sense now. I'd be interested in having the option for this to be the default functionality for **all** domains but I suppose I can just handle that myself by trimming to the host before querying the API.

**Comment by mat** [comment]
Yes, trimming on the client side should give exactly the same behaviour.

If I get around  to it any time soon I'd like to add wildcard support for HOST_ONLY_DOMAINS entries, so one could have just a single entry `*` to achieve this.

**Comment by odebroqueville** [comment]
Wouldn't it be possible to test if there's a favicon available at www.example.com/some/page.html and, if not, look for an icon at www.example.com. When neither exist, then provide a letter, as is currently the case (if I understood correctly). I'm often getting letters where icons do exist on the main domain (e.g. 
dogpile: href="http://cdn3.inspsearchapi.com/dogpile/11.2.0.421/favicon.ico",
eBay: href="https://pages.ebay.com/favicon.ico",
Google Maps (maps.google.com): href="https://www.google.com/images/branding/product/ico/maps_32dp.ico",
Lilo (search.lilo.org): href="https://www.lilosearch.org/img/newlogo/lilo16.png",
Twitter: href="https://abs.twimg.com/favicons/favicon.ico")

**Comment by mat** [comment]
@odebroqueville see #35, these should be solved now.
